### ISSUE TITLE
Request: documentation example for a write-only derived atom

### ISSUE THREAD

**Issue by rodrigocfd** [jotaijs/jotai-immer#2]
There are a few examples in the official documentation page:

* https://jotai.org/docs/integrations/immer

However, no example for a [write-only derived atom](https://github.com/pmndrs/jotai#write-only-derived-atoms), which is probably the main reason for using Immer – updating a complex and deep state.

I'm a bit lost here, so I believe it would be nice to have an example in the official docs.

**Comment by dai-shi** [comment]
I think jotai-immer is mainly for primitive atoms. It can't be used with write-only atoms.
Though, it might be easy to use `produce` from immer without jotai-immer.
```js
const objAtom = atom({});
const updateAtom = atom(null, (get, set, updater) => {
  set(objAtom, produce(updater));
});
```

**Comment by rodrigocfd** [comment]
Okay, thanks.
