### ISSUE TITLE
Feature request: implement useSetImmerAtom to return only setState

### ISSUE THREAD

**Issue by idrm** [jotaijs/jotai-immer#3]
The `useImmerAtom` hook returns both the atom value and a `setState` function. This forces unnecessary re-renders in components that only require `setState` and do not depend on the atom value.
 
Would you consider adding a `useSetImmerAtom` hook that returns only the `setState` function?

Here's an implementation based on `useImmerAtom`:

```ts
export function useSetImmerAtom<Value, Result>(
  anAtom: WritableAtom<Value, [(value: Value) => Value], Result>,
  scope?: Scope
) {
  const setState = useSetAtom(anAtom, scope)
  const setStateWithImmer = useCallback(
    (fn: (draft: Draft<Value>) => void) => setState(produce(fn)),
    [setState]
  )
  return setStateWithImmer
}
```

**Comment by dai-shi** [comment]
Yeah, I think it's reasonable to add `useSetImmerAtom`.
`useImmerAtom` should be refactored to use it internally.

Would you like to work on it?

**Comment by idrm** [comment]
Sure, I can submit a PR.

You want the updated `useImmerAtom` to, essentially, return `[useAtomValue(atom, scope), useSetImmerAtom(atom, scope)]`?

**Comment by dai-shi** [comment]
Thanks.

We should actually update the second argument signature.
```js
// options can be `{ scope }`.
function useImmerAtom(atom, options) {
  return [useAtomValue(atom, options), useSetImmerAtom(atom, options)];
}
```
(requires jotai >= 2.0.0)

**Comment by idrm** [comment]
Covered by https://github.com/jotaijs/jotai-immer/pull/4
